gamenews/urls.py
"""
url configuration for gamenews project
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("report/", include("report.urls"), name="report-urls"),
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path("", include("news.urls"), name="news-urls"),
    path('summernote/', include('django_summernote.urls')),
]

news/urls.py
"""
url patterns for news app
"""
from django.urls import path
from . import views


urlpatterns = [
    path('', views.ThreadList.as_view(), name='threadlist'),
    path('<slug:slug>/', views.thread_detail, name='thread_detail'),
    path('welcome-to-the-site/', views.thread_detail, name='about_us'),
    path('<slug:slug>/edit_response/<int:response_id>',
         views.response_edit, name='response_edit'),
    path('<slug:slug>/delete_response/<int:response_id>',
         views.response_delete, name='response_delete'),
]

report/urls.py
"""urls for report app"""
from django.urls import path
from . import views


# url patterns for report app
urlpatterns = [
    path('', views.report_guide, name='report'),
]

news/models.py
"""models for the news app"""
from django.db import models
from django.contrib.auth.models import User


class Thread(models.Model):
    """
    Stores a thread post related to the User model
    """
    title = models.CharField(max_length=150, unique=True, blank=False)
    slug = models.SlugField(max_length=200, unique=True)
    poster = models.ForeignKey(User, on_delete=models.RESTRICT,
                               related_name="news_posts")
    body = models.TextField(blank=False)
    posted_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-posted_on"]

    """returns a string representation of thread"""
    def __str__(self):
        return f"{self.title} - {self.poster}"


class Response(models.Model):
    """
    Stores a reponse post related to the Thread model
    """
    poster = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    thread = models.ForeignKey(Thread, on_delete=models.RESTRICT,
                               related_name="responses")
    content = models.TextField(blank=False)
    posted_on = models.DateTimeField(auto_now_add=True)
    visible = models.BooleanField(default=True)

    class Meta:
        ordering = ["posted_on"]

    """returns a string representation of thread"""
    def __str__(self):
        return f"{self.content} - {self.poster}"

report/models.py
"""models for report app"""
from django.db import models


class Report(models.Model):
    """
    Stores the guidelines on reporting users
    """
    title = models.CharField(max_length=250)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField(blank=False)

    def __str__(self):
        return self.title


class ReportUser(models.Model):
    """
    Stores a report post on a specific user
    """
    thread_url = models.URLField(blank=False)
    user_being_reported = models.CharField(blank=False, max_length=250)
    reason_for_report = models.TextField(blank=False)
    reporters_email = models.EmailField(blank=False)
    examined = models.BooleanField(default=False)

news/forms.py
"""forms for the news app"""
from django import forms
from .models import Response, Thread


# form to respond to posts
class ResponseForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = ('content',)

report/forms.py
"""forms for the report app"""
from django import forms
from .models import ReportUser


# form to report users
class ReportUserForm(forms.ModelForm):
    class Meta:
        model = ReportUser
        fields = ('thread_url', 'user_being_reported',
                  'reason_for_report', 'reporters_email',)

news/views.py
"""views for news app"""
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Thread, Response
from .forms import ResponseForm


class ThreadList(generic.ListView):
    """
    Displays all objects in the Threads model
    """
    queryset = Thread.objects.all()
    template_name = "news/index.html"
    paginate_by = 5


def thread_detail(request, slug):
    """
    Display an individual thread.

    **Context**

    ``thread``
        An instance of :model:`news.Thread`
    ``responses``
        all responses related to the thread
    ``reponse_count``
        The number of responses to the thread
    ``response_form``
        The form to post responses
    **Template:**

    :template:`news/thread_detail.html`
    """

    queryset = Thread.objects.all()
    thread = get_object_or_404(queryset, slug=slug)
    responses = thread.responses.filter(visible=True).order_by("posted_on")
    response_count = thread.responses.filter().count()
    if request.method == "POST":
        response_form = ResponseForm(data=request.POST)
        if response_form.is_valid():
            response = response_form.save(commit=False)
            response.poster = request.user
            response.thread = thread
            messages.add_message(request, messages.SUCCESS, 'Response posted!')
            response.save()
            return HttpResponseRedirect(reverse("thread_detail", args=[slug]))

    response_form = ResponseForm()

    return render(
        request,
        "news/thread_detail.html",
        {
            "thread": thread,
            "responses": responses,
            "response_count": response_count,
            "response_form": response_form,
            },
    )


def response_edit(request, slug, response_id):
    """
    view to edit responses

    **Context**

    ``thread``
        An instance of :model:`news.Thread`
    ``response``
        a response related to the thread
    ``response_form``
        The form to edit responses
    """
    if request.method == "POST":

        queryset = Response.objects.filter(visible=True)
        thread = get_object_or_404(Thread, slug=slug)
        response = get_object_or_404(queryset, pk=response_id)
        response_form = ResponseForm(data=request.POST, instance=response)

        if response_form.is_valid() and response.poster == request.user:
            response = response_form.save(commit=False)
            response.thread = thread
            response.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Response updated!')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Error updating response!')

    return HttpResponseRedirect(reverse('thread_detail', args=[slug]))


def response_delete(request, slug, response_id):
    """
    view to delete responses

    **Context**

    ``thread``
        An instance of :model:`news.Thread`
    ``response``
        a response related to the thread
    """
    queryset = Response.objects.filter(visible=True)
    thread = get_object_or_404(Thread, slug=slug)
    response = get_object_or_404(queryset, pk=response_id)

    if response.poster == request.user:
        response.delete()
        messages.add_message(request, messages.SUCCESS, 'Response deleted!')
    else:
        messages.add_message(request, messages.ERROR,
                             "You cannot delete others' responses!")

    return HttpResponseRedirect(reverse('thread_detail', args=[slug]))

report/views.py
"""views for the report app"""
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Report
from .forms import ReportUserForm


@login_required()
def report_guide(request):
    """
    Display the report page.

    **Context**

    ``report``
        An instance of :model:`report.Report`
    ``report_user``
        The form to post reports
    **Template:**

    :template:`news/report.html`
    """
    report = Report.objects.all().order_by('-updated_on').first()
    report_user = ReportUserForm()
    if request.method == "POST":
        report_user_form = ReportUserForm(data=request.POST)
        if report_user_form.is_valid():
            report_user_form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Thank you for submitting a report.')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Error, could not submit report!')

    return render(
        request,
        "report/report.html",
        {"report": report,
            "report_user": report_user},
    )

news/templates/news/index.html
{% extends "base.html" %}
{% block content%}

<!-- Start of index.html content -->
<div class="container">
    <div class="card colorcard mt-3 pt-2 pb-4">
        <div class="block mt-3">
            <div class="block-body">
                {% for thread in thread_list %}
                <div>
                    <div class="col-8">
                        <a href="{% url 'thread_detail' thread.slug %}" class="thread-link">
                            <h2>{{ thread.title }}</h2>
                        </a>
                        <div class="poster">
                            <p class="text-end">Posted By: <strong>{{ thread.poster }}</strong> on
                                <strong>{{ thread.posted_on}}</strong></p>
                        </div>
                        <hr>
                    </div>
                    {% if forloop.counter|divisibleby:3 %}
                </div>
                <div class="row">
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>
</div>
</div>

<!-- index.html content ends here -->

{% endblock%}

news/templates/news/thread_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="text-center">
        <!-- Thread title-->
        <h1 class="thread-title" id="title">{{ thread.title }}</h1>
      </div>
      <!-- Thread poster and date of posting-->
      <div class="text-start">
        <h2>Posted by: {{ thread.poster }}</h2>
        <p>Posted on: {{ thread.posted_on }}</p>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col card colorcard mt-3">
      <div class="card-body" >
        <div>
        <!-- Thread body -->
        <div class="card-text" id="thread{{ thread.id }}">
          {{ thread.body | safe }}
        </div>
        <hr>
      </div>
      </div>
    </div>
  </div>
</div>

<!-- Responses to thread -->
<div class="container">
  <div class="row mt-3">
    <h3>Responses: {{ response_count }}</h3>
  </div>
  <div class="row" >
    <div class="col card colorcard">
      <div class="card-body" >
        <div>
          {% for response in responses %}
          <div>
            <p><strong>
                {{ response.poster }} {{response.posted_on}}
              </strong>
            </p>
            <div id="response{{ response.id }}">
              {{ response.content | linebreaks }}
            </div>
            {% if user.is_authenticated and response.poster == user %}
            <button class="btn edit-response btn-dark" data-response_id="{{ response.id }}" aria-label="Edit response">Edit Response</button>
            <button class="btn delete-response btn-dark" data-response_id="{{ response.id }}" aria-label="Delete response">Delete Response</button>
            {% endif %}
            <hr>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>        

<!-- Posting new responses -->
<div class="container">
  <div class="row">
    <div class="col-12 card colorcard mb-4 mt-3">
      <div class="card-body">
        {% if user.is_authenticated %}
        <h3>Post a response:</h3>
        <p>Let us know your thoughts on this!</p>
        <p>Posting as: {{ user.username }}</p>
        <form id="responseForm" method="post" style="margin-top: 1.3em;">
          {{ response_form | crispy }}
          {% csrf_token %}
          <button id="submitButton" type="submit" class="btn btn-submit btn-dark" aria-label="Submit response">Submit Response</button>
        </form>
        {% else %}
        <p>Log in to post a response</p>
        {% endif %}
      </div>
    </div>
  </div>
</div>


<!-- Modal to confirm deletion of response -->
<div class="modal fade" id="deleteResponse" tabindex="-1" aria-labelledby="deleteResponseLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteResponseLabel">Delete Response</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark" data-bs-dismiss="modal">No</button>
        <a id="deleteConfirm" href="#" class="btn
          btn-danger">Yes</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block extras %}
<script src="{% static 'js/responses.js' %}"></script>
{% endblock %}

report/templates/report/report.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="container">
  <div class="row my-4">
    <div class="col-10">
      <!-- Guidelines for how reporting should be used -->
      <h2>{{ report.title }}</h2>
      {{ report.content | safe }}
    </div>
  </div>
  <div class="row">
    <div class="col-8">
      <!-- Show date of last update to guidelines -->
      <p class="text-start"><em>Updated on: {{ report.updated_on }}</em></p>
    </div>
  </div>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="card col-10 py-2 colorcard">
      <div>
        <h2 class="text-center">Report User</h2>
        <!-- Form to report users -->
        <form method="post">
          {{ report_user | crispy }}
          {% csrf_token %}
          <button class="btn btn-dark" type="submit" aria-label="Submit report">Submit Report</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}
{% url 'threadlist' as home_url %}
{% url 'report' as report_url %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
    content="Project Game provides a discussion forum for those interested in gaming">
    <meta name="keywords"
      content="gaming, video games, technology, gaming blog, forum, gaming forum, news, gaming news, indie games, game development">
    <meta name="author" content="Hugh Keenan">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Jersey+15&family=Nanum+Gothic:wght@400;700;800&family=Pixelify+Sans:wght@400..700&family=Quicksand:wght@300..700&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap"
        rel="stylesheet">
    <!--Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!--Fontawesome CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" rel="stylesheet">
    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!--Favicon-->
    <link rel="icon" type="image/png" href="{% static 'images/favicons/icons8-game-color-16.png' %}" sizes="16x16">
    <link rel="icon" type="image/png" href="{% static 'images/favicons/icons8-game-color-32.png' %}" sizes="32x32">
    <link rel="icon" type="image/png" href="{% static 'images/favicons/favicon-48x48.png' %}" sizes="48x48">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/apple-touch-icon.png' %}">
    <title>Project Game</title>
</head>

<body>
    <header>
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-black">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'threadlist' %}" aria-label="Link to home page"><span
                        class="sitename">Project Game</span></a>
            </div>
            <div class="row navbar-margin">
                <div class="navbar-button">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarInfo"
                        aria-controls="navbarInfo" aria-expanded="false" aria-label="Navbar toggler">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="navbarInfo">
                    <ul class="navbar-nav mr-auto mt-auto navlist">
                        <li class="nav-item-active">
                        <a class="nav-link
                      {% if request.path == home_url %}active" aria-current="page{%endif%}"
                            href="{% url 'threadlist' %}" aria-label="Link to home page">Home</a>
                        </li>
                        <li class="nav-item-active">
                        <a class="nav-link
                      {% if request.path == about_us %}active" aria-current="page{%endif%}"
                            href="{% url 'about_us' %}" aria-label="Link to information page">About Us</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item-active">
                            <a class="nav-link
                      {% if request.path == report_url %}active" aria-current="page{%endif%}" href="{% url 'report' %}"
                                aria-label="Link to report user page" target="_blank">Report User</a>
                        </li>
                        <li class="nav-item-active">
                            <a class="nav-link {% if request.path == logout_url %}active" aria-current="page{% endif %}"
                                href="{% url 'account_logout' %}" aria-label="Link to logout page">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item-active">
                            <a class="nav-link {% if request.path == login_url %}active" aria-current="page{% endif %}"
                                href="{% url 'account_login' %}" aria-label="Link to login page">Login</a>
                        </li>
                        <li class="nav-item-active">
                            <a class="nav-link {% if request.path == signup_url %}active" aria-current="page{% endif %}"
                                href="{% url 'account_signup' %}" aria-label="Link to register page">Register</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!-- message display -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible
                    fade show messagebox" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                        aria-label="Close message"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!--Main body-->
    <main>
        {% if user.is_authenticated %}
        <span class="text-end signInNotice">Logged in as {{user}}</span>
        {% else %}
        <span class="text-end signInNotice">You are not logged in</span>
        {%endif%}

        {% block content %}
        <!-- Page content -->
        {% endblock content %}
    </main>

    {% if is_paginated %}
    <nav aria-label="Navigation between pages">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous page">
                    Previous</a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next page"> Next</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}

    <!--Footer-->
    <footer class="col-12 pb-1 bg-black">
        <p class="text-center footertext">Follow us for more:</p>
        <p class="text-center">
            <a href="https://www.facebook.com/" target="_blank" rel="noopener"
                aria-label="Visit Project Game's Facebook page"><i class="link-light fa-brands fa-facebook-f"></i></a>
            <a href="https://www.instagram.com/" target="_blank" rel="noopener"
                aria-label="Visit Project Game's Instagram page"><i
                    class="link-light fa-brands fa-square-instagram"></i></a>
            <a href="https://www.youtube.com/" target="_blank" rel="noopener"
                aria-label="Visit Project Game's Youtube page"><i class="link-light fa-brands fa-youtube"></i></a>
        </p>
        <p class="text-center footertext">Copyright Hugh Keenan 2024</p>
    </footer>

    <script src="//cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>

    {% block extras %}
    {% endblock %}

</body>

</html>

templates/mfa/authenticate.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <p>
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    </p>
    <form class="authenticate"
          method="POST"
          action="{% url 'mfa_authenticate' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Sign In" %}</button>
    </form>
{% endblock content %}

templates/mfa/index.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <section class="totp">
        <h2>{% translate "Authenticator App" %}</h2>
        {% if authenticators.totp %}
            <p>{% translate "Authentication using an authenticator app is active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_deactivate_totp' %}">{% translate "Deactivate" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "An authenticator app is not active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_activate_totp' %}">{% translate "Activate" %}</a>
                </li>
            </ul>
        {% endif %}
    </section>
    <section class="recovery_codes">
        <h2>{% translate "Recovery Codes" %}</h2>
        {% if authenticators.recovery_codes %}
            <p>
                {% blocktranslate with total_count=authenticators.recovery_codes.generate_codes|length count unused_count=authenticators.recovery_codes.get_unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
            </p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_view_recovery_codes' %}">{% translate "View codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "No recovery codes set up." %}</p>
        {% endif %}
    </section>
{% endblock content %}

templates/mfa/recovery_codes/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account. This action will invalidate your existing codes. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_generate_recovery_codes' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Generate" %}</button>
    </form>
{% endblock content %}

templates/mfa/recovery_codes/index.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate count unused_count=unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
    </p>
    {% if unused_codes %}
        <textarea class="recovery-codes" rows="{{ unused_codes|length }}" readonly>{% for code in unused_codes %}{{ code }}
{% endfor %}
</textarea>
    {% endif %}
    <ul class="actions">
        {% if unused_codes %}
            <li>
                <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
            </li>
        {% endif %}
        <li>
            <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
        </li>
    </ul>
{% endblock content %}

templates/mfa/totp/activate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Activate Authenticator App" %}</h1>
    {{ totp_svg|safe }}
    <form method="POST" action="{% url 'mfa_activate_totp' %}">
        {% csrf_token %}
        <p>
            <label>{% translate "Authenticator secret" %}:</label>
            <input type="text"
                   disabled="disabled"
                   value="{{ form.secret }}"
                   size="{{ form.secret|length }}">
        </p>
        {{ form.as_p }}
        <button type="submit">{% trans "Activate" %}</button>
    </form>
{% endblock content %}

templates/mfa/totp/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}

templates/mfa/totp/deactivate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Deactivate Authenticator App" %}</h1>
    <p>
        {% blocktranslate %}You are about to deactivate authenticator app based authentication. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_deactivate_totp' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Deactivate" %}</button>
    </form>
{% endblock content %}